// common
export const UPDATE_LOADING_STATUS = 'UPDATE_LOADING_STATUS'
export const AJAX_FUN = 'AJAX_FUN'
export const ADD_INVENTORY_DATA = 'ADD_INVENTORY_DATA'
export const UPDATE_INVENTORY_DATA = 'UPDATE_INVENTORY_DATA'
export const DELETE_INVENTORY_DATA = 'DELETE_INVENTORY_DATA'
export const DELETE_ALL_INVENTORY_DATA = 'DELETE_ALL_INVENTORY_DATA'
